PREFIX geo: <http://www.geonames.org/ontology#>
PREFIX pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?concept (geo:Feature AS ?type) ?code ?latitude ?longitude ?ancestors ?population WHERE {
    ?concept rdf:type geo:Feature.
    ?concept geo:featureCode ?code.
    ?concept geo:featureClass ?class.
    ?concept pos:lat ?latitude.
    ?concept pos:long ?longitude.
    OPTIONAL { ?concept geo:population ?population }

    # allow only specific classes and codes globally
    FILTER(?class = geo:A || ?class = geo:P
        || ?type = geo:H.OCN || ?type = geo:H.SEA
        || ?type = geo:L.AREA || ?type = geo:L.CONT || ?type = geo:L.RGN
        || ?type = geo:S.CMTY || ?type = geo:S.HSTS || ?type = geo:S.MNMT || ?type = geo:S.MUS || ?type = geo:S.PRN || ?type = geo:S.RUIN
        || ?type = geo:T.ISL || ?type = geo:T.PEN
        || ?type = geo:V.FRST
    )

    # allow only specific codes or locations in specific countries
    {
        ?concept geo:countryCode ?country.
        FILTER(?type = geo:A.ADM1 || ?type = geo:A.ADM1H
            || ?type = geo:A.PCL || ?type = geo:A.PCLD || ?type = geo:A.PCLF || ?type = geo:A.PCLH || ?type = geo:A.PCLI || ?type = geo:A.PCLS
            || ?type = geo:H.STM
            || ?type = geo:P.PPLC || ?type = geo:P.PPLCH || ?type = geo:P.PPLA
            || ?type = geo:S.SCH
            || ?country = "AL"
            || ?country = "AT"
            || ?country = "BA"
            || ?country = "BE"
            || ?country = "BG"
            || ?country = "BY"
            || ?country = "CS"
            || ?country = "CZ"
            || ?country = "DE"
            || ?country = "EE"
            || ?country = "FR"
            || ?country = "GB"
            || ?country = "GR"
            || ?country = "HR"
            || ?country = "HU"
            || ?country = "IL"
            || ?country = "IT"
            || ?country = "LT"
            || ?country = "LV"
            || ?country = "MD"
            || ?country = "ME"
            || ?country = "MK"
            || ?country = "NL"
            || ?country = "PL"
            || ?country = "RO"
            || ?country = "RS"
            || ?country = "RU"
            || ?country = "SI"
            || ?country = "SK"
            || ?country = "UA"
            || ?country = "US"
            || ?country = "XK"
        )

    } UNION {
        OPTIONAL { ?concept geo:countryCode ?country }
        FILTER(!BOUND(?country))
    }

    # get all ancestors transitively
    ?concept geo:parentFeature+ ?ancestors.
}