PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gn: <http://www.geonames.org/ontology#>

SELECT ?concept ?type ?literal WHERE {
    ?concept rdf:type gn:Feature.
    ?concept gn:featureCode ?type.
    ?concept gn:name | gn:officialName | gn:alternateName ?literal.
}
