PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?concept ?type (COUNT(?literal) AS ?numLabels) ?latitude ?longitude ?name ?country ?ancestors ?population ?wikipediaLinks ?otherLinks WHERE {
    ?concept rdf:type gn:Feature.
    ?concept gn:featureCode ?type.
    ?concept gn:name | gn:officialName | gn:alternateName ?literal.

    ?concept wgs84_pos:lat ?latitude.
    ?concept wgs84_pos:long ?longitude.
    ?concept gn:name ?name.
    ?concept gn:countryCode ?country.
    ?concept gn:parentFeature+ ?ancestors.
    OPTIONAL { ?concept gn:population ?population. }
    OPTIONAL { ?concept gn:wikipediaArticle ?wikipediaLinks. }
    OPTIONAL { ?concept rdfs:seeAlso ?otherLinks. FILTER(!STRSTARTS(STR(?otherLinks), "http://sws.geonames.org/")). }
} GROUP BY ?concept ?type ?latitude ?longitude ?name ?country ?ancestors ?population ?wikipediaLinks ?otherLinks
